### ISSUE TITLE
[Trust issues] - Why my script is not working? 

### ISSUE THREAD

**Issue by LautaroJayat** [Sheryx00/report-with-stock-pickings#1]
Why my code is not working? could you help me?

**Comment by Sheryx00** [comment]
Sure share me your secrets

**Comment by LautaroJayat** [comment]
I wont share my code nor my secrets with you. I don't trust you.

**Comment by LautaroJayat** [comment]
Thx for merging #2 , these changes will save me lot of time.
I can trust you.
You are my friend now https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Ftse3.mm.bing.net%2Fth%3Fid%3DOIP._zRwRyfg8JIyituuWI5SwQHaIY%26pid%3DApi&f=1&ipt=9d47c670754d2105e64ea36775b33c475d928c41eac80d28517bb74dabf2d505&ipo=images
